import {
  Bot,
  BriefcaseBusiness,
  Building2,
  Crown,
  Database,
  FileText,
  Gauge,
  Gift,
  Inbox,
  Languages,
  LayoutDashboard,
  Route,
  Send,
  Settings,
  Shield,
  Sparkles,
  Trophy,
  UserRound,
  UsersRound,
  WalletCards,
} from "lucide-react";

export const navItems = [
  { href: "/dashboard", label: "Dashboard", icon: LayoutDashboard },
  { href: "/onboarding", label: "AI-подбор", icon: Route },
  { href: "/feed", label: "Reels-лента", icon: Inbox },
  { href: "/profile", label: "Профиль", icon: UserRound },
  { href: "/profile/resumes", label: "Резюме", icon: FileText },
  { href: "/crm", label: "CRM", icon: UsersRound },
  { href: "/leaderboard", label: "Рейтинг", icon: Trophy },
  { href: "/settings", label: "Настройки", icon: Settings },
];

export const onboardingSteps = [
  { title: "Вход", detail: "Google или email-код", status: "done" },
  { title: "Цель", detail: "Работа или клиенты", status: "done" },
  { title: "Рассказ", detail: "Голос, буфер или текст", status: "active" },
  { title: "Рынок", detail: "СНГ или Global", status: "active" },
  { title: "Платформы", detail: "Выбор площадок", status: "next" },
  { title: "Лента", detail: "Reels + Tinder карточки", status: "next" },
];

export const stats = [
  { label: "Подходящих карточек", value: "128", trend: "+18 за неделю", icon: Gauge },
  { label: "AI-откликов", value: "42", trend: "74% открытий", icon: Sparkles },
  { label: "В CRM", value: "19", trend: "6 активных переговоров", icon: BriefcaseBusiness },
  { label: "Токены", value: "3 / 20", trend: "+5 за Telegram", icon: WalletCards },
];

export const opportunities = [
  {
    id: "card_hh_frontend",
    jobId: "job_frontend_hh",
    platformId: "hh",
    platform: "hh.ru",
    title: "Frontend Developer",
    company: "B2B SaaS команда",
    market: "СНГ",
    marketType: "cis",
    language: "Русский",
    type: "Работа",
    score: 92,
    budget: "180 000 - 220 000 ₽",
    tags: ["React", "TypeScript", "Next.js"],
    filters: ["IT", "frontend", "remote", "middle", "React"],
    url: "https://hh.ru/search/vacancy?text=Frontend%20Developer",
    summary: "Удаленная роль в продуктовой команде. Нужны интерфейсы, компоненты, работа с API и аккуратная поддержка design system.",
  },
  {
    id: "card_habr_qa",
    jobId: "job_frontend_hh",
    platformId: "habr",
    platform: "Хабр Карьера",
    title: "Junior QA Engineer",
    company: "EdTech платформа",
    market: "СНГ",
    marketType: "cis",
    language: "Русский",
    type: "Работа",
    score: 84,
    budget: "80 000 - 120 000 ₽",
    tags: ["QA", "Web", "Manual"],
    filters: ["IT", "junior", "QA", "без опыта", "удаленка"],
    url: "https://career.habr.com/vacancies?q=Junior%20QA",
    summary: "Стартовая IT-роль для внимательного человека: тест-кейсы, баг-репорты, проверка веб-интерфейсов и обучение внутри команды.",
  },
  {
    id: "card_fl_crm",
    jobId: "job_react_fl",
    platformId: "fl",
    platform: "FL.ru",
    title: "CRM и личный кабинет",
    company: "Малый бизнес",
    market: "СНГ",
    marketType: "cis",
    language: "Русский",
    type: "Клиент",
    score: 88,
    budget: "120 000 - 180 000 ₽",
    tags: ["CRM", "React", "API"],
    filters: ["разработка", "CRM", "личный кабинет", "оплата", "срок 3 недели"],
    url: "https://www.fl.ru/projects/",
    summary: "Нужен исполнитель, который быстро соберёт личный кабинет, роли пользователей, оплату и базовую аналитику для менеджеров.",
  },
  {
    id: "card_kwork_landing",
    jobId: "job_react_fl",
    platformId: "kwork",
    platform: "Kwork",
    title: "Лендинг для IT-услуги",
    company: "Founder",
    market: "СНГ",
    marketType: "cis",
    language: "Русский",
    type: "Клиент",
    score: 79,
    budget: "45 000 - 70 000 ₽",
    tags: ["Landing", "Copy", "Tilda/Next.js"],
    filters: ["лендинг", "IT", "быстрый запуск", "форма заявки"],
    url: "https://kwork.ru/projects",
    summary: "Нужен лендинг для новой услуги: понятный оффер, блоки доверия, форма заявки и базовая SEO-подготовка.",
  },
  {
    id: "card_upwork_saas",
    jobId: "job_react_fl",
    platformId: "upwork",
    platform: "Upwork API-бот",
    title: "React SaaS dashboard",
    company: "US startup",
    market: "Global",
    marketType: "global",
    language: "English",
    type: "Client",
    score: 91,
    budget: "$4k-$7k",
    tags: ["React", "Dashboard", "Payments"],
    filters: ["Upwork API", "React", "SaaS", "Stripe", "English"],
    url: "https://www.upwork.com/nx/search/jobs/?q=react%20saas",
    summary: "A client needs a product dashboard, billing flow, and onboarding screens. The card should arrive through an Upwork API bot integration.",
  },
  {
    id: "card_linkedin_support",
    jobId: "job_frontend_hh",
    platformId: "linkedin",
    platform: "LinkedIn",
    title: "Technical Support Specialist",
    company: "Remote-first SaaS",
    market: "Global",
    marketType: "global",
    language: "English",
    type: "Job",
    score: 82,
    budget: "$2k-$3.5k",
    tags: ["Support", "SaaS", "English"],
    filters: ["remote", "support", "IT", "English B1-B2"],
    url: "https://www.linkedin.com/jobs/search/?keywords=technical%20support%20specialist",
    summary: "Entry-friendly IT role: help users, write tickets, reproduce bugs, and communicate with product and engineering teams.",
  },
  {
    id: "card_telegram_bot",
    jobId: "job_react_fl",
    platformId: "telegram",
    platform: "Telegram",
    title: "Telegram bot for lead capture",
    company: "Service agency",
    market: "СНГ",
    marketType: "cis",
    language: "Русский",
    type: "Клиент",
    score: 86,
    budget: "90 000 - 130 000 ₽",
    tags: ["Telegram Bot", "Next.js", "CRM"],
    filters: ["bot", "лиды", "CRM", "уведомления"],
    url: "https://t.me/s/freelancehunt",
    summary: "Нужно связать Telegram-бота, форму заявки и CRM, чтобы менеджеры видели лиды и статусы в одном месте.",
  },
];

export const crmItems = [
  { name: "Frontend Developer", stage: "Отправлено", owner: "AI + сайт", value: "12 токенов", next: "Follow-up завтра" },
  { name: "CRM и личный кабинет", stage: "Просмотрено", owner: "Telegram", value: "8 токенов", next: "Уточнить бюджет" },
  { name: "React SaaS dashboard", stage: "Получен ответ", owner: "Иван", value: "$4k", next: "Discovery call" },
  { name: "Telegram bot for lead capture", stage: "Приглашение", owner: "AI scout", value: "6 токенов", next: "Сгенерировать письмо" },
];

export const tokenActions = [
  ["Лайк вакансии/проекта", "1 токен"],
  ["Генерация отклика", "1 токен"],
  ["Сопроводительное письмо", "1 токен"],
  ["Улучшение резюме", "2 токена"],
  ["Анализ вакансии", "1 токен"],
];

export const leaderboard = [
  { name: "arkadiy.dev", role: "Frontend Developer", points: 1800, wins: 7 },
  { name: "design_hero", role: "Product Designer", points: 1500, wins: 5 },
  { name: "react_master", role: "React Engineer", points: 1200, wins: 4 },
  { name: "ui_ux_king", role: "UX Designer", points: 1100, wins: 4 },
  { name: "code_samurai", role: "Full Stack", points: 1000, wins: 3 },
];

export const adminMetrics = [
  { label: "Users", value: "2 418", icon: UsersRound },
  { label: "Markets", value: "12", icon: Building2 },
  { label: "Languages", value: "9", icon: Languages },
  { label: "Active bots", value: "3", icon: Crown },
];

export const stackItems = [
  { label: "Frontend", value: "Next.js, TypeScript, Tailwind CSS, shadcn/ui", icon: LayoutDashboard },
  { label: "Backend", value: "Node.js, Serverless Functions, API Gateway", icon: Database },
  { label: "AI", value: "OpenAI / Claude API for scoring and replies", icon: Sparkles },
  { label: "Telegram", value: "Bot API notifications and phone verification", icon: Bot },
  { label: "Tokens", value: "Balance, transactions, refill, limits", icon: WalletCards },
  { label: "Referral", value: "+10 / +5 token incentives", icon: Gift },
  { label: "Applications", value: "Replies, statuses, saved resumes", icon: Send },
  { label: "Security", value: "JWT, 2FA, rate limiting, anti-spam", icon: Shield },
];
